# SwiftLint Configuration
# Enforces coding standards including no emoji usage

# Disable rules we don't want
disabled_rules:
  - trailing_whitespace # Allow some flexibility
  - todo # Allow TODO comments for development
  - unused_import # Sometimes needed for conditional compilation

# Enable additional rules
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - convenience_type
  - discouraged_object_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - file_header
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - let_var_whitespace
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - no_space_in_method_call
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Include all Swift files
included:
  - SpeechDictation
  - SpeechDictationTests
  - SpeechDictationUITests

# Exclude generated and third-party code
excluded:
  - Carthage
  - Pods
  - build
  - .build
  - DerivedData

# Custom rules
custom_rules:
  no_emoji:
    name: "No Emoji"
    regex: '[\u{1F600}-\u{1F64F}\u{1F300}-\u{1F5FF}\u{1F680}-\u{1F6FF}\u{1F1E0}-\u{1F1FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}\u{1F900}-\u{1F9FF}\u{1F018}-\u{1F270}]'
    message: "Emojis are not allowed in the codebase. Use descriptive text or SF Symbols instead."
    severity: error
    
  no_emoji_in_comments:
    name: "No Emoji in Comments"
    regex: '//.*[\u{1F600}-\u{1F64F}\u{1F300}-\u{1F5FF}\u{1F680}-\u{1F6FF}\u{1F1E0}-\u{1F1FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}\u{1F900}-\u{1F9FF}\u{1F018}-\u{1F270}]'
    message: "Emojis are not allowed in comments. Use descriptive text instead."
    severity: error
    
  no_emoji_in_strings:
    name: "No Emoji in String Literals"
    regex: '"[^"]*[\u{1F600}-\u{1F64F}\u{1F300}-\u{1F5FF}\u{1F680}-\u{1F6FF}\u{1F1E0}-\u{1F1FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}\u{1F900}-\u{1F9FF}\u{1F018}-\u{1F270}][^"]*"'
    message: "Emojis are not allowed in string literals. Use descriptive text or localized strings instead."
    severity: warning  # Warning for strings since they might be user-facing

# Line length
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

# Function length
function_body_length:
  warning: 50
  error: 100

# File length
file_length:
  warning: 400
  error: 500

# Type name
type_name:
  min_length: 3
  max_length: 40
  excluded:
    - ID
    - URL
    - UUID

# Identifier name
identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - url
    - x
    - y
    - z

# Nesting levels
nesting:
  type_level:
    warning: 3
    error: 5
  statement_level:
    warning: 5
    error: 10

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 20

# Reporter type
reporter: "xcode" 